# Generated by Django 4.2.13 on 2024-07-05 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaSeguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=50)),
                ('icono', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Auditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntidadAuditada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.TextField()),
                ('responsable', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InformeAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.auditor')),
                ('entidad_auditada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.entidadauditada')),
            ],
        ),
        migrations.CreateModel(
            name='SeccionAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_referencia', models.CharField(max_length=20)),
                ('descripcion_control', models.TextField()),
                ('estado', models.CharField(max_length=20)),
                ('evidencia', models.FileField(upload_to='media/')),
                ('observaciones', models.TextField()),
                ('recomendaciones', models.TextField()),
                ('area_seguridad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.areaseguridad')),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.informeauditoria')),
            ],
        ),
    ]
