# Generated by Django 4.2.13 on 2024-07-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_estado_remove_areaseguridad_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccionauditoria',
            name='evidencia',
            field=models.FileField(upload_to=''),
        ),
    ]
