# Generated by Django 4.2.13 on 2024-07-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_seccionauditoria_evidencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='informeauditoria',
            name='motivo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seccionauditoria',
            name='codigo_referencia',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='seccionauditoria',
            name='evidencia',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='seccionauditoria',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seccionauditoria',
            name='recomendaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
