# Generated by Django 4.2.13 on 2024-07-05 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_informeauditoria_motivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='seccionauditoria',
            name='pregunta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seccionauditoria',
            name='respuesta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seccionauditoria',
            name='quien_responde',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secciones_responsables', to='api.persona'),
        ),
    ]
