# Generated by Django 4.2.13 on 2024-07-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_persona_seccionauditoria_pregunta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='rol',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
