# Generated by Django 4.2.13 on 2024-07-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_persona_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='informeauditoria',
            name='area',
            field=models.TextField(blank=True, null=True),
        ),
    ]
