# Generated by Django 4.2.13 on 2024-07-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_informeauditoria_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccionauditoria',
            name='codigo_referencia',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
